// vue-composition-todolist/src/components/TodoListApp.vue
<template>
  <div class="hello">
    <section class="todoapp">
      <header class="header">
        <h1>todolist</h1>
        <add-todo @onAddTodo="addTodo"/>
      </header>
      <todo-list
        :totalCount="todos.length"
        :visibleTodos="visibleTodos"
        :activeTodoCount="activeTodoCount"
        :todoBeingEdited="todoBeingEdited"
        @onStartEditTodo="startEditTodo"
        @onEndEditTodo="endEditTodo"
        @onDestroyTodo="destroyTodo"
        @onToggleAllTodo="toggleAllTodo"
      />
      <filter-todo
        :totalCount="todos.length"
        :activeTodoCount="activeTodoCount"
        :completedTodoCount="completedTodoCount"
        :visibilityFilter="visibilityFilter"
        @onFilterChange="setVisibilityFilter"
        @onClearCompletedTodo="clearCompletedTodo"
      />
    </section>
    <footer class="info">
      <p>Double-click to edit a todo</p>
      <p>TodoList based on vue</p>
      <p>Source:
        <a href="https://github.com/he-zhiyong/todolist/tree/master/vue-composition-todolist"> GitHub </a>or
        <a href="https://gitee.com/he-zhiyong/todolist/tree/master/vue-composition-todolist"> Gitee </a>
      </p>
    </footer>
  </div>
</template>

<script lang="ts">
import 'todomvc-app-css/index.css'
import { createComponent, reactive, computed, Ref, toRefs } from '@vue/composition-api'
import { Todo, State } from './types'
import AddTodo from './AddTodo.vue'
import TodoList from './TodoList.vue'
import FilterTodo from './FilterTodo.vue'

export default createComponent({
  name: 'TodoListApp',
  components: {
    AddTodo,
    TodoList,
    FilterTodo
  },
  setup () {
    const state: any = reactive<State>({
      todos: getLocalStorageTodos(),
      visibilityFilter: 'all',
      todoBeingEdited: null,
      visibleTodos: computed<Todo[]>(() => {
        switch (state.visibilityFilter) {
          case 'all':
            return state.todos
          case 'active':
            return state.todos.filter((todo: Todo) => !todo.completed)
          case 'completed':
            return state.todos.filter((todo: Todo) => todo.completed)
          default:
            return state.todos
        }
      }),
      activeTodoCount: computed<number>(() => {
        return state.todos.reduce(
          (sum :number, todo: Todo) => sum + (todo.completed ? 0 : 1),
          0
        )
      }),
      completedTodoCount: computed<number>(() => {
        return state.todos.length - state.activeTodoCount
      })
    })

    function getLocalStorageTodos () {
      let todos: Todo[] = JSON.parse(localStorage.getItem('todos') || '[]')
      return todos
    }
    function saveTodosToLocalStorage () {
      localStorage.setItem('todos', JSON.stringify(state.todos))
    }
    function addTodo (text: string) {
      state.todos.push({
        text,
        id: Date.now().toString(),
        completed: false
      })
    }
    function startEditTodo (todo: Todo) {
      state.todoBeingEdited = todo
    }
    function endEditTodo (newTodo: Todo) {
      state.todos.forEach((todo: Todo) => {
        if (todo.id === newTodo.id) {
          todo = newTodo
        }
      })
      state.todoBeingEdited = null
    }
    function toggleAllTodo (checked: boolean) {
      state.todos.forEach((todo :Todo) => {
        todo.completed = checked
      })
    }
    function destroyTodo (id: Todo['id']) {
      state.todos = state.todos.filter(
        (todo: Todo) => todo.id !== id
      )
      state.todoBeingEdited = null
    }
    function setVisibilityFilter (filterName: State['visibilityFilter']) {
      state.visibilityFilter = filterName
    }
    function clearCompletedTodo () {
      state.todos = state.todos.filter(
        (todo :Todo) => todo.completed === false
      )
    }
    window.onbeforeunload = () => {
      saveTodosToLocalStorage()
    }
    return {
      ...toRefs(state),
      addTodo,
      startEditTodo,
      endEditTodo,
      toggleAllTodo,
      destroyTodo,
      setVisibilityFilter,
      clearCompletedTodo
    }
  }
})
</script>

// react-redux-todolist/src/containers/TodoListApp.js
import 'todomvc-app-css/index.css';
import React, { Component } from 'react';
import AddTodo from '../components/AddTodo';
import TodoList from '../components/TodoList';
import FilterTodo from '../components/FilterTodo';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';
import { addTodo, toggleTodo, toggleAllTodo,startEditTodo, endEditTodo, cancelEditTodo, destroyTodo, clearCompletedTodo,setVisibilityFilter, VisibilityFilters } from '../actions';

class TodoListApp extends Component {
  render() {
    // Injected by connect() call:
    const { dispatch, todos, visibleTodos, visibilityFilter, todoBeingEdited, activeTodoCount, completedTodoCount} = this.props;
    return (
      <div>
        <section className="todoapp">
          <header className="header">
            <h1>todolist</h1>
            <AddTodo
              onAddTodo={text =>
                dispatch(addTodo(text))
            } />
          </header>
          <TodoList
            todos={todos}
            visibleTodos={visibleTodos}
            todoBeingEdited={todoBeingEdited}
            activeTodoCount={activeTodoCount}
            onToggleTodo={id =>
              dispatch(toggleTodo(id))
            }
            onToggleAllTodo={checked =>
              dispatch(toggleAllTodo(checked))
            }
            onStartEditTodo={(todo) =>
              dispatch(startEditTodo(todo))
            }
            onEndEditTodo={(id,text) =>
              dispatch(endEditTodo(id,text))
            }
            onCancelEditTodo={() =>
              dispatch(cancelEditTodo())
            }
            onDestroyTodo={id =>
              dispatch(destroyTodo(id))
            } 
          />
          <FilterTodo
            todoFilter={visibilityFilter}
            activeTodoCount={activeTodoCount}
            completedTodoCount={completedTodoCount}
            onFilterChange={filter =>
              dispatch(setVisibilityFilter(filter))
            } 
            onClearCompletedTodo={() => 
              dispatch(clearCompletedTodo())
            } 
          />
        </section>
        <footer className="info">
          <p>Double-click to edit a todo</p>
          <p>TodoList based on react and redux,Debug with redux-devtools</p>
          <p>Source: 
            <a href="https://github.com/he-zhiyong/todolist/tree/master/react-redux-todolist"> GitHub </a>or
            <a href="https://gitee.com/he-zhiyong/todolist/tree/master/react-redux-todolist"> Gitee</a>
          </p>
        </footer>
      </div>
    )
  }
};

TodoListApp.propTypes = {
  visibleTodos: PropTypes.arrayOf(PropTypes.shape({
    text: PropTypes.string.isRequired,
    id: PropTypes.string.isRequired,
    completed: PropTypes.bool.isRequired
  }).isRequired).isRequired,
  visibilityFilter: PropTypes.oneOf([
    'SHOW_ALL',
    'SHOW_COMPLETED',
    'SHOW_ACTIVE'
  ]).isRequired,
  todoBeingEdited: PropTypes.object,
  activeTodoCount: PropTypes.number.isRequired,
  completedTodoCount: PropTypes.number.isRequired
}

function getVisibleTodos(todos, filter) {
  switch (filter) {
    case VisibilityFilters.SHOW_ALL:
      return todos;
    case VisibilityFilters.SHOW_COMPLETED:
      return todos.filter(todo => todo.completed);
    case VisibilityFilters.SHOW_ACTIVE:
      return todos.filter(todo => !todo.completed);
    default:
      return todos;
  }
}

function getActiveTodoCount(todos) {
  return todos.reduce(
    (sum, todo) => sum + (todo.completed ? 0 : 1),
    0
  )
}

function getCompletedTodoCount(todos,activeTodoCount) {
  return todos.length - activeTodoCount;
}

// Which props do we want to inject, given the global state?
// Note: use https://github.com/faassen/reselect for better performance.
function select(state) {
  return {
    todos:state.todos,
    visibleTodos: getVisibleTodos(state.todos, state.visibilityFilter),
    visibilityFilter: state.visibilityFilter,
    todoBeingEdited: state.todoBeingEdited,
    activeTodoCount:getActiveTodoCount(state.todos),
    completedTodoCount:getCompletedTodoCount(state.todos,getActiveTodoCount(state.todos))
  }
}

// 包装 component ，注入 dispatch 和 state 到其默认的 connect(select)(TodoListApp) 中；
export default connect(select)(TodoListApp);
