// vue-composition-todolist/src/components/AddTodo.vue
<template>
  <input
    class="new-todo"
    placeholder="What needs to be done?"
    autofocus autocomplete="off"
    v-model="newTodoText"
    @keydown.enter="handleAddTodoKeyDown"
  />
</template>

<script lang="ts">
import { createComponent, ref } from '@vue/composition-api'

export default createComponent({
  name: 'AddTodo',
  setup (props, { emit }) {
    const newTodoText = ref('')

    function handleAddTodoKeyDown () {
      if (newTodoText.value.trim()) {
        emit('onAddTodo', newTodoText.value.trim())
        newTodoText.value = ''
      }
    }

    return {
      newTodoText,
      handleAddTodoKeyDown
    }
  }
})
</script>

// react-hooks-todolist/src/components/AddTodo.tsx
import React from 'react'
import { Todo } from './types'

const ENTER_KEY = 13
interface Props {
  onAddTodo: (text: Todo['text']) => void
}
const AddTodo: React.FC<Props> = (props: Props) => {
  const handleAddTodoKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.keyCode !== ENTER_KEY) return
    event.preventDefault()
    const newTodo = event.target as HTMLInputElement
    const newTodoText = newTodo.value.trim()
    if (newTodoText.trim()) {
      props.onAddTodo(newTodoText)
      newTodo.value = ''
    }
  }

  return (
    <input 
      className="new-todo"
      type="text"
      placeholder="What needs to be done?"
      autoFocus={true}
      onKeyDown={handleAddTodoKeyDown}
    />
  )
}

export default AddTodo
