// vue-composition-todolist/src/components/FilterTodo.vue
<template>
  <footer class="footer" v-show="totalCount">
    <span class="todo-count">
      <strong>{{activeTodoCount}}</strong> {{activeTodoCount>1?'items':'item'}} left
    </span>
    <ul class="filters">
      <li><a @click="handleFilterChange('all')" :class="{ selected: visibilityFilter == 'all' }">All</a></li>
      <li><a @click="handleFilterChange('active')" :class="{ selected: visibilityFilter == 'active' }">Active</a></li>
      <li><a @click="handleFilterChange('completed')" :class="{ selected: visibilityFilter == 'completed' }">Completed</a></li>
    </ul>
    <button class="clear-completed" @click="handleClearCompletedTodo" v-show="completedTodoCount > 0">
      Clear completed
    </button>
  </footer>
</template>

<script lang="ts">
import { createComponent, ref, computed, SetupContext } from '@vue/composition-api'
import { Todo, State } from './types'

interface Props {
  totalCount: number
  activeTodoCount: State['activeTodoCount']
  completedTodoCount: State['completedTodoCount']
  visibilityFilter: State['visibilityFilter']
}
export default createComponent({
  name: 'FilterTodo',
  props: {
    totalCount: {
      type: Number,
      required: true
    },
    activeTodoCount: {
      type: Number,
      required: true
    },
    completedTodoCount: {
      type: Number,
      required: true
    },
    visibilityFilter: {
      type: String,
      required: true
    }
  },
  setup (props: Props, { emit } :SetupContext) {
    function handleFilterChange (filterName: Props['visibilityFilter']) {
      emit('onFilterChange', filterName)
    }
    function handleClearCompletedTodo () {
      emit('onClearCompletedTodo')
    }

    return {
      handleFilterChange,
      handleClearCompletedTodo
    }
  }
})
</script>

// react-hooks-todolist/src/components/FilterTodo.tsx
import React from 'react'
import { State } from './types'

interface Props {
  visibilityFilter: State['visibilityFilter']
  activeTodoCount: State['activeTodoCount']
  completedTodoCount: State['completedTodoCount']
  onFilterChange: (filterName: State['visibilityFilter']) => void
  onClearCompletedTodo: () => void
}
const FilterTodo: React.FC<Props> = (props: Props) => {
  const { visibilityFilter, activeTodoCount, completedTodoCount, onFilterChange, onClearCompletedTodo } = props
  if (!activeTodoCount && !completedTodoCount) return null

  
  const renderFilter = (filterName: State['visibilityFilter'], caption: string) => {
    return (
			<li>
        <a
          onClick={() => onFilterChange(filterName)}
          className={filterName === visibilityFilter ? "selected" : ""}>
					{caption}
				</a>
				{' '}
			</li>
		)
  }

  return (
    <footer className="footer">
      <span className="todo-count">
        <strong>{activeTodoCount}</strong> {activeTodoCount > 1 ? 'items' : 'item'} left
      </span>
      <ul className="filters">
        {renderFilter('all', 'All')}
        {renderFilter('active', 'Active')}
        {renderFilter('completed', 'Completed')}
      </ul>
      {completedTodoCount === 0
        ? null
        : <button
            className="clear-completed"
            onClick={onClearCompletedTodo}>
            Clear completed
          </button>
      }
    </footer>
  )
}

export default FilterTodo
