// vue-composition-todolist/src/components/TodoList.vue
<template>
  <section class="main" v-show="totalCount" v-cloak>
    <input id="toggleAll" class="toggle-all" type="checkbox" v-model="toggleAllTodo">
    <label for="toggleAll"></label>
    <ul class="todo-list">
      <Todo class="todo" v-for="todo in visibleTodos"
        :key="todo.id"
        :todo="todo"
        :todoBeingEdited="todoBeingEdited"
        @onStartEditTodo="onStartEditTodo"
        @onEndEditTodo="onEndEditTodo"
        @onDestroyTodo="onDestroyTodo"
      />
    </ul>
  </section>
</template>

<script lang="ts">
import { createComponent, ref, computed, SetupContext } from '@vue/composition-api'
import { Todo, State } from './types'
import TodoComponent from './Todo.vue'

interface Props {
  totalCount: number
  visibleTodos: State['visibleTodos']
  activeTodoCount: State['activeTodoCount']
  todoBeingEdited: State['todoBeingEdited']
}
export default createComponent({
  name: 'TodoList',
  components: {
    Todo: TodoComponent
  },
  props: {
    totalCount: {
      type: Number,
      required: true
    },
    visibleTodos: {
      type: Array,
      required: true
    },
    activeTodoCount: {
      type: Number,
      required: true
    },
    todoBeingEdited: {
      type: Object,
      required: false
    }
  },
  setup (props: Props, { emit }: SetupContext) {
    const { activeTodoCount } = props
    const toggleAllTodo = computed({
      get: function () {
        return activeTodoCount === ref(0)
      },
      set: function (checked) {
        emit('onToggleAllTodo', checked)
      }
    })

    function onStartEditTodo (todo: Todo) {
      emit('onStartEditTodo', todo)
    }
    function onEndEditTodo (id: Todo['id'], text: Todo['text']) {
      emit('onEndEditTodo', id, text)
    }
    function onDestroyTodo (id: Todo['id']) {
      emit('onDestroyTodo', id)
    }

    return {
      toggleAllTodo,
      onStartEditTodo,
      onEndEditTodo,
      onDestroyTodo
    }
  }
})
</script>

<style scoped>
  [v-cloak] { display: none; }
</style>

// react-hooks-todolist/src/components/TodoList.tsx
import React from 'react'
import TodoComponent from './Todo'
import { Todo, State } from './types'

interface Props {
  totalCount: number
  visibleTodos: State['todos']
  todoBeingEdited: State['todoBeingEdited']
  activeTodoCount: State['activeTodoCount']
  onToggleTodo: (id: Todo['id']) => void
  onToggleAllTodo: (checked: boolean) => void
  onStartEditTodo: (todo: Todo) => void
  onEndEditTodo: (id: Todo['id'], text: Todo['text']) => void
  onCancelEditTodo: () => void
  onDestroyTodo: (id: Todo['id']) => void
}
const TodoList: React.FC<Props> = (props: Props) => {
  const { totalCount, visibleTodos, todoBeingEdited, activeTodoCount, onToggleTodo, onToggleAllTodo, onStartEditTodo, onEndEditTodo, onCancelEditTodo, onDestroyTodo } = props

  const handleToggleAllTodo = (event: React.ChangeEvent<HTMLInputElement>) => {
    let checked = event.target.checked
    onToggleAllTodo(checked)
  }
  return (
    <section className="main" style={{'display': totalCount > 0 ? 'block':'none' }}>
        <input
          id="toggleAll"
          className="toggle-all"
          type="checkbox"
          onChange={handleToggleAllTodo}
          checked={activeTodoCount === 0}
        />
        <label htmlFor="toggleAll"></label>
        <ul className="todo-list">
          {visibleTodos.map(todo =>
            <TodoComponent 
              key={todo.id}
              todo={todo}
              todoBeingEdited={todoBeingEdited}
              onToggleTodo={() => onToggleTodo(todo.id)} 
              onStartEditTodo={() => onStartEditTodo(todo)} 
              onEndEditTodo={(text) => onEndEditTodo(todo.id,text)} 
              onCancelEditTodo={() => onCancelEditTodo()}
              onDestroyTodo={() => onDestroyTodo(todo.id)} 
            />
          )}
        </ul>
      </section>
  )
}

export default TodoList
