// vue-composition-todolist/src/components/Todo.vue
<template>
  <li :class="{ completed: todo.completed, editing: todo == todoBeingEdited }">
    <div class="view">
      <input class="toggle" type="checkbox" v-model="todo.completed">
      <label @dblclick="handleStartEditTodo(todo)">{{ todo.text }}</label>
      <button class="destroy" @click="handleDestroyTodo(todo)"></button>
    </div>
    <input class="edit" type="text"
      v-model="editText"
      v-todo-focus="todo == todoBeingEdited"
      @blur="handleEndEditTodo(todo)"
      @keyup.enter="handleEndEditTodo(todo)"
      @keyup.esc="handleCancelEditTodo(todo)">
  </li>
</template>

<script lang="ts">
import { createComponent, ref, computed, SetupContext } from '@vue/composition-api'
import { Todo, State } from './types'

interface Props {
  todo: Todo
  todoBeingEdited: State['todoBeingEdited']
}
export default createComponent({
  name: 'Todo',
  props: {
    todo: {
      type: Object,
      required: true
    },
    todoBeingEdited: {
      type: Object,
      required: false
    }
  },
  setup (props: Props, { emit } :SetupContext) {
    const editText = ref('')

    function handleStartEditTodo (todo: Todo) {
      editText.value = todo.text.trim()
      emit('onStartEditTodo', todo)
    }
    function handleEndEditTodo (todo: Todo) {
      if (!props.todoBeingEdited) {
        return
      }
      let text = editText.value.trim()
      if (text) {
        todo.text = text
        emit('onEndEditTodo', todo)
      } else {
        emit('onDestroyTodo', todo.id)
      }
    }
    function handleCancelEditTodo (todo: Todo) {
      emit('onEndEditTodo', todo)
    }
    function handleDestroyTodo (todo: Todo) {
      emit('onDestroyTodo', todo.id)
    }

    return {
      editText,
      handleStartEditTodo,
      handleEndEditTodo,
      handleCancelEditTodo,
      handleDestroyTodo
    }
  },
  directives: {
    'todo-focus': function (el: any, binding: any) {
      if (binding.value) {
        el.focus()
      }
    }
  }
})
</script>

// react-hooks-todolist/src/components/Todo.tsx
import React, { useEffect } from 'react'
import { Todo, State } from './types'

const ESCAPE_KEY = 27
const ENTER_KEY = 13

interface Props {
  key: string
  todo: Todo
  todoBeingEdited: State['todoBeingEdited']
  onToggleTodo: () => void
  onStartEditTodo: () => void
  onEndEditTodo: (text: Todo['text']) => void
  onCancelEditTodo: () => void
  onDestroyTodo: () => void
}
const TodoComponent: React.FC<Props> = (props: Props) => { 
  const { todo, todoBeingEdited, onToggleTodo, onStartEditTodo, onEndEditTodo, onCancelEditTodo, onDestroyTodo } = props
  let editField: HTMLInputElement | null = null

  useEffect(() => {
    if (todoBeingEdited) editField!.focus()
    return () => {}
  }, [editField, todoBeingEdited])

  const handleEditTodo = () => {
    editField!.value = todo.text
    onStartEditTodo()
  }
  const handleSubmit = (destroy?: boolean) => {
    let text = editField!.value.trim()
		if (text) {
			onEndEditTodo(text)
		} else if (destroy) {
			onDestroyTodo()
		}
  }
  const handleKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.which === ESCAPE_KEY) {
			onCancelEditTodo()
		} else if (event.which === ENTER_KEY) {
			handleSubmit(true)
		}
  }

  return (
    <li className={[
      todo.completed ? "completed" : "",
      todo === todoBeingEdited ? "editing" : ""
    ].join(" ")}>
      <div className="view">
        <input
          className="toggle"
          type="checkbox"
          checked={todo.completed}
          onChange={onToggleTodo}
        />
        <label onDoubleClick={handleEditTodo}>
          {todo.text}
        </label>
        <button className="destroy" onClick={onDestroyTodo} />
      </div>
      <input
        ref={input => editField = input}
        className="edit"
        autoFocus={true} 
        onBlur={() => handleSubmit()}
        onKeyDown={handleKeyDown}
      />
    </li>
  )
}

export default TodoComponent
