// angular-todolist/src/app/FilterTodo/filtertodo.component.ts
import {Component, OnInit, Input, Output, EventEmitter} from '@angular/core';

@Component({
  selector: 'filter-todo',
  templateUrl: './filtertodo.component.html'
})
export class FilterTodoComponent{
  @Input() visibilityFilter: string;
  @Input() activeTodoCount: number;
  @Input() completedTodoCount: number;
  @Output() onFilterChange = new EventEmitter();
  @Output() onClearCompletedTodo = new EventEmitter();

  handleFilterChange(filterName){
    this.onFilterChange.emit(filterName);
  }

  handleClearCompletedTodo(){
    this.onClearCompletedTodo.emit();
  }
}

<footer class="footer">
  <span class="todo-count">
    <strong>{{activeTodoCount}}</strong> {{ activeTodoCount > 1? 'items':'item'}} left
  </span>
  <ul class="filters">
    <li><a (click)="handleFilterChange('all')" class="{{visibilityFilter == 'all'? 'selected':''}}">All</a></li>
    <li><a (click)="handleFilterChange('active')" class="{{visibilityFilter == 'active'? 'selected':''}}">Active</a></li>
    <li><a (click)="handleFilterChange('completed')" class="{{visibilityFilter == 'completed'? 'selected':''}}">Completed</a></li>
  </ul>
  <button class="clear-completed" *ngIf="completedTodoCount"
    (click)="handleClearCompletedTodo()"
  >
    Clear completed
  </button>
</footer>

// vue-todolist/src/components/FilterTodo.vue
<template>
  <footer class="footer" v-show="todos.length">
    <span class="todo-count">
      <strong>{{activeTodoCount}}</strong> {{activeTodoCount>1?'items':'item'}} left
    </span>
    <ul class="filters">
      <li><a @click="handleFilterChange('all')" :class="{ selected: visibilityFilter == 'all' }">All</a></li>
      <li><a @click="handleFilterChange('active')" :class="{ selected: visibilityFilter == 'active' }">Active</a></li>
      <li><a @click="handleFilterChange('completed')" :class="{ selected: visibilityFilter == 'completed' }">Completed</a></li>
    </ul>
    <button class="clear-completed" @click="handleClearCompletedTodo" v-show="completedTodoCount > 0">
      Clear completed
    </button>
  </footer>
</template>

<script>
  export default {
    name:'FilterTodo',
    props:{
      todos:{
        type:Array,
        required:true
      },
      activeTodoCount:{
        type:Number,
        required:true
      },
      completedTodoCount:{
        type:Number,
        required:true
      },
      visibilityFilter:{
        type:String,
        required:true
      }
    },
    methods:{
      handleFilterChange(filterName){
        this.$emit('onFilterChange', filterName)
      },
      handleClearCompletedTodo(){
        this.$emit('onClearCompletedTodo')
      }
    }
  }
</script>
