// angular-todolist/src/app/TodoList/todolist.component.ts
import {Component, OnInit, Input, Output, EventEmitter} from '@angular/core';

import { Todo } from '../todo';

@Component({
  selector: 'todo-list',
  templateUrl: './todolist.component.html'
})
export class TodoListComponent{
  @Input() todos:Array<Todo>;
  @Input() visibleTodos:Array<Todo>;
  @Input() activeTodoCount:number;
  @Input() todoBeingEdited:any;
  @Output() onToggleTodo = new EventEmitter();
  @Output() onToggleAllTodo = new EventEmitter();
  @Output() onStartEditTodo = new EventEmitter();
  @Output() onEndEditTodo = new EventEmitter();
  @Output() onDestroyTodo = new EventEmitter();

  handleToggleTodo(id){
    this.onToggleTodo.emit(id)
  }

  handleToggleAllTodo(checked){
    this.onToggleAllTodo.emit(checked)
  }

  handleStartEditTodo(todo){
    this.onStartEditTodo.emit(todo)
  }

  handleEndEditTodo(todo){
    this.onEndEditTodo.emit(todo)
  }

  handleDestroyTodo(id){
    this.onDestroyTodo.emit(id)
  }
}

<section class="main" *ngIf="todos.length">
  <input id="toggleAll" class="toggle-all" type="checkbox"
    [ngModel]="activeTodoCount === 0"
    (ngModelChange)="handleToggleAllTodo($event)"
  >
  <label for="toggleAll"></label>
  <ul class="todo-list">
    <todo *ngFor="let todo of visibleTodos"
      [todo] = todo
      [todoBeingEdited] = todoBeingEdited
      (onToggleTodo)="handleToggleTodo($event)"
      (onStartEditTodo)="handleStartEditTodo($event)"
      (onEndEditTodo)="handleEndEditTodo($event)"
      (onDestroyTodo)="handleDestroyTodo($event)"
    >
    </todo>
  </ul>
</section>

// vue-todolist/src/components/TodoList.vue
<template>
  <section class="main" v-show="todos.length" v-cloak>
    <input id="toggleAll" class="toggle-all" type="checkbox" v-model="toggleAllTodo">
    <label for="toggleAll"></label>
    <ul class="todo-list">
      <Todo class="todo" v-for="todo in visibleTodos"
        :key="todo.id"
        :todo="todo"
        :todoBeingEdited="todoBeingEdited"
        @onStartEditTodo="onStartEditTodo"
        @onEndEditTodo="onEndEditTodo"
        @onDestroyTodo="onDestroyTodo"
      >
      </Todo>
    </ul>
  </section>
</template>

<script>
  import Todo from './Todo'

  export default {
    name:'TodoList',
    components: {
      Todo
    },
    props:{
      todos:{
        type:Array,
        required:true
      },
      visibleTodos:{
        type:Array,
        required:true
      },
      activeTodoCount:{
        type:Number,
        required:true
      },
      todoBeingEdited:{
        type:Object,
        required:false
      }
    },
    methods:{
      onStartEditTodo(todo){
        this.$emit('onStartEditTodo', todo)
      },
      onEndEditTodo(id,text){
        this.$emit('onEndEditTodo', id, text)
      },
      onDestroyTodo(id){
        this.$emit('onDestroyTodo', id)
      }
    },
    computed:{
      toggleAllTodo: {
        get: function () {
          return this.activeTodoCount === 0
        },
        set: function (checked) {
          this.$emit('onToggleAllTodo', checked)
        }
      }
    }
  }
</script>

<style scoped>
  [v-cloak] { display: none; }
</style>
