// vue-composition-todolist/src/components/TodoListApp.vue
<template>
  <div class="hello">
    <section class="todoapp">
      <header class="header">
        <h1>todolist</h1>
        <add-todo @onAddTodo="addTodo"/>
      </header>
      <todo-list
        :totalCount="todos.length"
        :visibleTodos="visibleTodos"
        :activeTodoCount="activeTodoCount"
        :todoBeingEdited="todoBeingEdited"
        @onStartEditTodo="startEditTodo"
        @onEndEditTodo="endEditTodo"
        @onDestroyTodo="destroyTodo"
        @onToggleAllTodo="toggleAllTodo"
      />
      <filter-todo
        :totalCount="todos.length"
        :activeTodoCount="activeTodoCount"
        :completedTodoCount="completedTodoCount"
        :visibilityFilter="visibilityFilter"
        @onFilterChange="setVisibilityFilter"
        @onClearCompletedTodo="clearCompletedTodo"
      />
    </section>
    <footer class="info">
      <p>Double-click to edit a todo</p>
      <p>TodoList based on vue</p>
      <p>Source:
        <a href="https://github.com/he-zhiyong/todolist/tree/master/vue-composition-todolist"> GitHub </a>or
        <a href="https://gitee.com/he-zhiyong/todolist/tree/master/vue-composition-todolist"> Gitee </a>
      </p>
    </footer>
  </div>
</template>

<script lang="ts">
import 'todomvc-app-css/index.css'
import { createComponent, reactive, computed, Ref, toRefs } from '@vue/composition-api'
import { Todo, State } from './types'
import AddTodo from './AddTodo.vue'
import TodoList from './TodoList.vue'
import FilterTodo from './FilterTodo.vue'

export default createComponent({
  name: 'TodoListApp',
  components: {
    AddTodo,
    TodoList,
    FilterTodo
  },
  setup () {
    const state: any = reactive<State>({
      todos: getLocalStorageTodos(),
      visibilityFilter: 'all',
      todoBeingEdited: null,
      visibleTodos: computed<Todo[]>(() => {
        switch (state.visibilityFilter) {
          case 'all':
            return state.todos
          case 'active':
            return state.todos.filter((todo: Todo) => !todo.completed)
          case 'completed':
            return state.todos.filter((todo: Todo) => todo.completed)
          default:
            return state.todos
        }
      }),
      activeTodoCount: computed<number>(() => {
        return state.todos.reduce(
          (sum :number, todo: Todo) => sum + (todo.completed ? 0 : 1),
          0
        )
      }),
      completedTodoCount: computed<number>(() => {
        return state.todos.length - state.activeTodoCount
      })
    })

    function getLocalStorageTodos () {
      let todos: Todo[] = JSON.parse(localStorage.getItem('todos') || '[]')
      return todos
    }
    function saveTodosToLocalStorage () {
      localStorage.setItem('todos', JSON.stringify(state.todos))
    }
    function addTodo (text: string) {
      state.todos.push({
        text,
        id: Date.now().toString(),
        completed: false
      })
    }
    function startEditTodo (todo: Todo) {
      state.todoBeingEdited = todo
    }
    function endEditTodo (newTodo: Todo) {
      state.todos.forEach((todo: Todo) => {
        if (todo.id === newTodo.id) {
          todo = newTodo
        }
      })
      state.todoBeingEdited = null
    }
    function toggleAllTodo (checked: boolean) {
      state.todos.forEach((todo :Todo) => {
        todo.completed = checked
      })
    }
    function destroyTodo (id: Todo['id']) {
      state.todos = state.todos.filter(
        (todo: Todo) => todo.id !== id
      )
      state.todoBeingEdited = null
    }
    function setVisibilityFilter (filterName: State['visibilityFilter']) {
      state.visibilityFilter = filterName
    }
    function clearCompletedTodo () {
      state.todos = state.todos.filter(
        (todo :Todo) => todo.completed === false
      )
    }
    window.onbeforeunload = () => {
      saveTodosToLocalStorage()
    }
    return {
      ...toRefs(state),
      addTodo,
      startEditTodo,
      endEditTodo,
      toggleAllTodo,
      destroyTodo,
      setVisibilityFilter,
      clearCompletedTodo
    }
  }
})
</script>

// react-todolist/src/components/TodoListApp.jsx
import 'todomvc-app-css/index.css';
import React, { Component } from 'react';
import AddTodo from './AddTodo';
import TodoList from './TodoList';
import FilterTodo from './FilterTodo';

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      todos:[],
      visibleTodos:[],
      visibilityFilter:'SHOW_ALL',
      todoBeingEdited:null,
      activeTodoCount:0,
      completedTodoCount:0
    };
  }
  
  componentWillMount(){
    const todos = JSON.parse(localStorage.getItem('todos')) || [];
    this.freshTodoList(todos);
    window.onbeforeunload = () => {
      let todos = this.state.todos;
      localStorage.setItem('todos', JSON.stringify(todos));
    };
  }

  render() {
    const { todos, visibleTodos, visibilityFilter, todoBeingEdited, activeTodoCount, completedTodoCount} = this.state;
    return (
      <div>
        <section className="todoapp">
          <header className="header">
            <h1>todolist</h1>
            <AddTodo
              onAddTodo={text =>
                this.addTodo(text)
            } />
          </header>
          <TodoList 
            todos={todos}
            visibleTodos={visibleTodos}
            todoBeingEdited={todoBeingEdited}
            activeTodoCount={activeTodoCount}
            onToggleTodo={id =>
              this.toggleTodo(id)
            }
            onToggleAllTodo={(checked) =>
              this.toggleAllTodo(checked)
            }
            onStartEditTodo={(todo) =>
              this.startEditTodo(todo)
            }
            onEndEditTodo={(id,text) =>
              this.endEditTodo(id,text)
            }
            onCancelEditTodo={() =>
              this.cancelEditTodo()
            }
            onDestroyTodo={id =>
              this.destroyTodo(id)
            } 
          />
          <FilterTodo 
            todoFilter={visibilityFilter}
            activeTodoCount={activeTodoCount}
            completedTodoCount={completedTodoCount}
            onFilterChange={filter =>
              this.setVisibilityFilter(filter)
            }
            onClearCompletedTodo={() => 
              this.clearCompletedTodo()
            } 
          />
        </section>
        <footer className="info">
          <p>Double-click to edit a todo</p>
          <p>TodoList based on react</p>
          <p>Source: 
            <a href="https://github.com/he-zhiyong/todolist/tree/master/react-todolist"> GitHub </a>or
            <a href="https://gitee.com/he-zhiyong/todolist/tree/master/react-todolist"> Gitee </a>
          </p>
        </footer>
      </div>
    )
  }

  freshTodoList(todos){
    let activeTodoCount = this.getActiveTodoCount(todos);
    let completedTodoCount = this.getCompletedTodoCount(todos,activeTodoCount);
    let visibleTodos = this.getVisibleTodos(todos,this.state.visibilityFilter);
    this.setState({
      todos,
      visibleTodos,
      activeTodoCount,
      completedTodoCount
    });
  }

  addTodo(text){
    let todos = this.state.todos;
    todos.push({
      text,
      id:Date.now().toString(),
      completed:false
    });
    this.freshTodoList(todos);
  }

  toggleTodo(id){
    let todos = this.state.todos;
    todos.forEach(todo => {
      if(todo.id === id){
        todo.completed = !todo.completed; 
      }
    })
    this.freshTodoList(todos);
  }

  toggleAllTodo(checked){
    let todos = this.state.todos;
    todos.forEach(
      todo => todo.completed = checked 
    )
    this.freshTodoList(todos);
  }

  startEditTodo(todo){
    this.setState({
			todoBeingEdited:todo
		});
  }

  endEditTodo(id,text){
    let todos = this.state.todos;
    todos.forEach(todo => {
      if(todo.id === id){
        todo.text = text; 
      }
    })
    this.freshTodoList(todos);
    this.setState({
			todoBeingEdited:null
		});
  }

  cancelEditTodo(){
    this.setState({
			todoBeingEdited:null
		});
  }
  
  destroyTodo(id){
    let todos = this.state.todos.filter(
			todo => todo.id !== id
    )  
    this.freshTodoList(todos);
  }
  
  setVisibilityFilter(filterName){
    let todos = this.state.todos;
    this.setState({
      visibleTodos:this.getVisibleTodos(todos,filterName),
      visibilityFilter:filterName
    });
  }

  clearCompletedTodo(){
    let todos = this.state.todos.filter(
			todo => todo.completed === false
    )  
    this.freshTodoList(todos);
  }
  
  getVisibleTodos(todos,filterName){
    switch (filterName) {
      case 'SHOW_ALL':
        return todos;
      case 'SHOW_COMPLETED':
        return todos.filter(todo => todo.completed);
      case 'SHOW_ACTIVE':
        return todos.filter(todo => !todo.completed);
      default:
        return todos;
    }
  }

  getActiveTodoCount(todos) {
		return todos.reduce(
			(sum, todo) => sum + (todo.completed ? 0 : 1),
			0
		)
  }
  
  getCompletedTodoCount(todos,activeTodoCount) {
		return todos.length - activeTodoCount;
  }
}

export default App;
