// vue-todolist/src/components/AddTodo.vue
<template>
  <input
    class="new-todo"
    placeholder="What needs to be done?"
    autofocus autocomplete="off"
    v-model="newTodoText"
    @keydown.enter="handleAddTodoKeyDown"
  />
</template>

<script>
  export default {
    name:'AddTodo',
    data(){
      return {
        newTodoText:''
      }
    },
    methods:{
      handleAddTodoKeyDown(){
        let newTodoText = this.newTodoText.trim()
        if(newTodoText){
          this.$emit('onAddTodo', newTodoText)
          this.newTodoText = ''
        }
      }
    }
  }
</script>

// angular-todolist/src/app/AddTodo/addtodo.component.ts
import { Component, OnInit, Output , NgModule, EventEmitter} from '@angular/core';

const ENTER_KEY = 13;

@Component({
  selector: 'add-todo',
  templateUrl: './addtodo.component.html'
})
export class AddTodoComponent{
  @Output() onAddTodo = new EventEmitter();
  newTodoText:string;

  handleAddTodoKeyDown(){
    let newTodoText = this.newTodoText.trim();
    if(newTodoText){
      this.onAddTodo.emit(newTodoText);
      this.newTodoText = '';
    }
  }
}

<input
  class="new-todo"
  placeholder="What needs to be done?"
  autofocus autocomplete="off"
  [(ngModel)]="newTodoText"
  (keydown.enter)="handleAddTodoKeyDown()"
>
