// react-redux-todolist/src/components/AddTodo.jsx
import React, { Component } from 'react';
import PropTypes from 'prop-types';

const ENTER_KEY = 13;

export default class AddTodo extends Component {
  render() {
    return (
      <input
        ref="newTodo"
        className="new-todo"
        placeholder="What needs to be done?"
        onKeyDown={this.handleAddTodoKeyDown}
        autoFocus={true}
      />
    )
  }

  handleAddTodoKeyDown = event => {
    if (event.keyCode !== ENTER_KEY) {
      return;
    }
    event.preventDefault();
    let newTodo = this.refs.newTodo;
    let newTodoText = newTodo.value.trim();
    if (newTodoText) {
      this.props.onAddTodo(newTodoText);
      newTodo.value = '';
    }
  }
}

AddTodo.propTypes = {
  onAddTodo: PropTypes.func.isRequired
}

// vue-composition-todolist/src/components/AddTodo.vue
<template>
  <input
    class="new-todo"
    placeholder="What needs to be done?"
    autofocus autocomplete="off"
    v-model="newTodoText"
    @keydown.enter="handleAddTodoKeyDown"
  />
</template>

<script lang="ts">
import { createComponent, ref } from '@vue/composition-api'

export default createComponent({
  name: 'AddTodo',
  setup (props, { emit }) {
    const newTodoText = ref('')

    function handleAddTodoKeyDown () {
      if (newTodoText.value.trim()) {
        emit('onAddTodo', newTodoText.value.trim())
        newTodoText.value = ''
      }
    }

    return {
      newTodoText,
      handleAddTodoKeyDown
    }
  }
})
</script>
