// angular-todolist/src/app/AddTodo/addtodo.component.ts
import { Component, OnInit, Output , NgModule, EventEmitter} from '@angular/core';

const ENTER_KEY = 13;

@Component({
  selector: 'add-todo',
  templateUrl: './addtodo.component.html'
})
export class AddTodoComponent{
  @Output() onAddTodo = new EventEmitter();
  private newTodoText:string;

  handleAddTodoKeyDown(value){
    let newTodoText = value.trim();
    if(newTodoText){
      this.onAddTodo.emit(newTodoText);
      this.newTodoText = '';
    }
  }
}

<input
  #newTodo
  class="new-todo"
  placeholder="What needs to be done?"
  autofocus autocomplete="off"
  [(ngModel)]="newTodoText"
  (keydown.enter)="handleAddTodoKeyDown(newTodo.value)"
>

// vue-composition-todolist/src/components/AddTodo.vue
<template>
  <input
    class="new-todo"
    placeholder="What needs to be done?"
    autofocus autocomplete="off"
    v-model="newTodoText"
    @keydown.enter="handleAddTodoKeyDown"
  />
</template>

<script lang="ts">
import { createComponent, ref } from '@vue/composition-api'

export default createComponent({
  name: 'AddTodo',
  setup (props, { emit }) {
    const newTodoText = ref('')

    function handleAddTodoKeyDown () {
      if (newTodoText.value.trim()) {
        emit('onAddTodo', newTodoText.value.trim())
        newTodoText.value = ''
      }
    }

    return {
      newTodoText,
      handleAddTodoKeyDown
    }
  }
})
</script>
