// react-redux-todolist/src/components/FilterTodo.jsx
import React, { Component } from 'react'
import PropTypes from 'prop-types';

export default class FilterTodo extends Component {
  render() {
    const { activeTodoCount, completedTodoCount} = this.props;
    
    if (!activeTodoCount && !completedTodoCount)
      return null;
      
    const activeTodoWord = activeTodoCount > 1 ? 'items' : 'item';
    
    return (
      <footer className="footer">
        <span className="todo-count">
          <strong>{activeTodoCount}</strong> {activeTodoWord} left
				</span>
        <ul className="filters">
          {this.renderFilter('SHOW_ALL', 'All')}
          {this.renderFilter('SHOW_ACTIVE', 'Active')}
          {this.renderFilter('SHOW_COMPLETED', 'Completed')}
        </ul>
        {completedTodoCount === 0
					? null
					: <button
							className="clear-completed"
							onClick={this.props.onClearCompletedTodo}>
							Clear completed
						</button>
				}
      </footer>
    )
  }

  renderFilter(filterName, caption) {
		return (
			<li>
        <a onClick={() => this.props.onFilterChange(filterName)}
          className={filterName === this.props.todoFilter ? "selected" : ""}>
					{caption}
				</a>
				{' '}
			</li>
		)
  }
}

FilterTodo.propTypes = {
  todoFilter: PropTypes.oneOf([
    'SHOW_ALL',
    'SHOW_COMPLETED',
    'SHOW_ACTIVE'
  ]).isRequired,
  activeTodoCount: PropTypes.number.isRequired,
  completedTodoCount: PropTypes.number.isRequired,
  onFilterChange: PropTypes.func.isRequired,
  onClearCompletedTodo: PropTypes.func.isRequired
}

// vue-composition-todolist/src/components/FilterTodo.vue
<template>
  <footer class="footer" v-show="totalCount">
    <span class="todo-count">
      <strong>{{activeTodoCount}}</strong> {{activeTodoCount>1?'items':'item'}} left
    </span>
    <ul class="filters">
      <li><a @click="handleFilterChange('all')" :class="{ selected: visibilityFilter == 'all' }">All</a></li>
      <li><a @click="handleFilterChange('active')" :class="{ selected: visibilityFilter == 'active' }">Active</a></li>
      <li><a @click="handleFilterChange('completed')" :class="{ selected: visibilityFilter == 'completed' }">Completed</a></li>
    </ul>
    <button class="clear-completed" @click="handleClearCompletedTodo" v-show="completedTodoCount > 0">
      Clear completed
    </button>
  </footer>
</template>

<script lang="ts">
import { createComponent, ref, computed, SetupContext } from '@vue/composition-api'
import { Todo } from './types'

interface Props {
  totalCount: number
  activeTodoCount: number
  completedTodoCount: number
  visibilityFilter: 'all' | 'active' | 'completed'
}
export default createComponent({
  name: 'FilterTodo',
  props: {
    totalCount: {
      type: Number,
      required: true
    },
    activeTodoCount: {
      type: Number,
      required: true
    },
    completedTodoCount: {
      type: Number,
      required: true
    },
    visibilityFilter: {
      type: String,
      required: true
    }
  },
  setup (props: Props, { emit } :SetupContext) {
    function handleFilterChange (filterName: Props['visibilityFilter']) {
      emit('onFilterChange', filterName)
    }
    function handleClearCompletedTodo () {
      emit('onClearCompletedTodo')
    }

    return {
      handleFilterChange,
      handleClearCompletedTodo
    }
  }
})
</script>
