// angular-todolist/src/app/TodoListApp/todolistapp.component.ts
import {Component, OnInit} from '@angular/core';

import { Todo } from '../Todo/todo';

@Component({
  selector: 'todo-list-app',
  templateUrl: './todolistapp.component.html'
})
export class TodoListAppComponent implements OnInit {
  todos: Array<Todo>;
  visibilityFilter: string;
  todoBeingEdited: object;
  activeTodoCount: number;
  constructor() { }

  ngOnInit() {
    this.todos =  JSON.parse(localStorage.getItem('todos')) || [];
    this.visibilityFilter = 'all';
    this.todoBeingEdited = null;
    this.activeTodoCount = 2
  }

  addTodo(e){
    console.log(e)
  }
}

<section class="todoapp">
  <header class="header">
    <h1>todolist</h1>
    <add-todo ></add-todo>
  </header>
  <todo-list
    [todos]="todos"
    [visibilityFilter]="visibilityFilter"
    [todoBeingEdited]="todoBeingEdited"
  >
  </todo-list>
  <filter-todo
    [visibilityFilter]="visibilityFilter"
    [activeTodoCount]="activeTodoCount"
  ></filter-todo>
</section>
<footer class="info">
  <p>Double-click to edit a todo</p>
  <p>TodoList based on angular</p>
  <p>Source:
    <a href="https://github.com/he-zhiyong/todolist/tree/master/angular-todolist"> GitHub </a>or
    <a href="https://gitee.com/he-zhiyong/todolist/tree/master/angular-todolist"> Gitee </a>
  </p>
</footer>

// vue-vuex-todolist/src/components/TodoListApp.vue
<template>
  <div>
    <section class="todoapp">
      <header class="header">
        <h1>todolist</h1>
        <add-todo></add-todo>
      </header>
      <todo-list></todo-list>
      <filter-todo></filter-todo>
    </section>
    <footer class="info">
      <p>Double-click to edit a todo</p>
      <p>TodoList based on vue and vuex</p>
      <p>Source:
        <a href="https://github.com/he-zhiyong/todolist/tree/master/vue-vuex-todolist"> GitHub </a>or
        <a href="https://gitee.com/he-zhiyong/todolist/tree/master/vue-vuex-todolist"> Gitee </a>
      </p>
    </footer>
  </div>
</template>

<script>
  import 'todomvc-app-css/index.css'
  import AddTodo from "./AddTodo"
  import TodoList from "./TodoList"
  import FilterTodo from "./FilterTodo"
  import { mapState, mapMutations } from 'vuex'

  export default {
    name:'TodoListApp',
    components: {
      AddTodo,
      TodoList,
      FilterTodo
    },
    methods:mapMutations(['saveTodosToLocalStorage']),
    computed:mapState(['todos']),
    created() {
      window.onbeforeunload = () => {
        this.saveTodosToLocalStorage(this.todos)
      }
    },
    /* watch: {
      todos: {
        handler: function () {
          this.saveTodosToLocalStorage()
        },
        deep: true
      }
    }, */
  }
</script>

<style>

</style>
