// vue-todolist/src/components/Todo.vue
<template>
  <li :class="{ completed: todo.completed, editing: todo == todoBeingEdited }">
    <div class="view">
      <input class="toggle" type="checkbox" v-model="todo.completed">
      <label @dblclick="handleStartEditTodo(todo)">{{ todo.text }}</label>
      <button class="destroy" @click="handleDestroyTodo(todo)"></button>
    </div>
    <input class="edit" type="text"
      v-model="editText"
      v-todo-focus="todo == todoBeingEdited"
      @blur="handleEndEditTodo(todo)"
      @keyup.enter="handleEndEditTodo(todo)"
      @keyup.esc="handleCancelEditTodo(todo)">
  </li>
</template>

<script>
  export default {
    name:'Todo',
    props:{
      todo:{
        type:Object,
        required:true
      },
      todoBeingEdited:{
        type:Object,
        required:false
      }
    },
    data(){
      return {
        editText:''
      }
    },
    methods:{
      handleStartEditTodo(todo){
        this.editText = todo.text.trim()
        this.$emit('onStartEditTodo', todo)
      },
      handleEndEditTodo(todo){
        if (!this.todoBeingEdited) {
          return
        }
        let text = this.editText.trim()
        if (text) {
          todo.text = text;
          this.$emit('onEndEditTodo', todo)
        } else {
          this.$emit('onDestroyTodo', todo.id)
        }
      },
      handleCancelEditTodo(todo){
        this.$emit('onEndEditTodo', todo)
      },
      handleDestroyTodo(todo){
        this.$emit('onDestroyTodo', todo.id)
      }
    },
    directives: {
      'todo-focus': function (el, binding) {
        if (binding.value) {
          el.focus()
        }
      }
    }
  }
</script>

// angular-todolist/src/app/Todo/todo.component.ts
import { Component, Input, Output, EventEmitter, ElementRef, Renderer } from '@angular/core';

import {Todo} from '../todo';
@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html'
  })
export class TodoComponent {
  @Input() todo: Todo;
  @Input() todoBeingEdited: any;
  @Output() onToggleTodo = new EventEmitter();
  @Output() onStartEditTodo = new EventEmitter();
  @Output() onEndEditTodo = new EventEmitter();
  @Output() onDestroyTodo = new EventEmitter();
  public editText: string;
  private editField: ElementRef;

  constructor(private el: ElementRef, private renderer: Renderer) {
    this.editField = el.nativeElement.children;
  }

  handleToggleTodo(todo): void {
    this.onToggleTodo.emit(todo.id);
  }

  handleStartEditTodo(todo): void {
    this.editText = todo.text;
    this.onStartEditTodo.emit(todo);
    this.editField[1].focus();
  }

  handleEndEditTodo(todo): void {
    if (!this.todoBeingEdited) {
      return;
    }
    const text: string = this.editText.trim();
    if (text) {
      todo.text = text;
      this.onEndEditTodo.emit(todo);
    } else {
      this.onDestroyTodo.emit(todo.id);
    }
  }

  handleCancelEditTodo(todo): void {
    this.onEndEditTodo.emit(todo);
  }

  handleDestroyTodo(todo): void {
    this.onDestroyTodo.emit(todo.id);
  }

}

<div class="view">
  <input class="toggle" type="checkbox"
    [ngModel]="todo.completed"
    (ngModelChange)="handleToggleTodo(todo)"
  >
  <label
    (dblclick)="handleStartEditTodo(todo)"
  >{{todo.text}}</label>
  <button class="destroy" (click)="handleDestroyTodo(todo)"></button>
</div>
<input class="edit" type="text" #editField
  [(ngModel)]="editText"
  (blur)="handleEndEditTodo(todo)"
  (keydown.enter)="handleEndEditTodo(todo)"
  (keydown.esc)="handleCancelEditTodo(todo)"
>
