// vue-composition-todolist/src/components/Todo.vue
<template>
  <li :class="{ completed: todo.completed, editing: todo == todoBeingEdited }">
    <div class="view">
      <input class="toggle" type="checkbox" v-model="todo.completed">
      <label @dblclick="handleStartEditTodo(todo)">{{ todo.text }}</label>
      <button class="destroy" @click="handleDestroyTodo(todo)"></button>
    </div>
    <input class="edit" type="text"
      v-model="editText"
      v-todo-focus="todo == todoBeingEdited"
      @blur="handleEndEditTodo(todo)"
      @keyup.enter="handleEndEditTodo(todo)"
      @keyup.esc="handleCancelEditTodo(todo)">
  </li>
</template>

<script lang="ts">
import { createComponent, ref, computed, SetupContext } from '@vue/composition-api'
import { Todo } from './types'

interface Props {
  todo: Todo
  todoBeingEdited: Todo | null
}
export default createComponent({
  name: 'Todo',
  props: {
    todo: {
      type: Object,
      required: true
    },
    todoBeingEdited: {
      type: Object,
      required: false
    }
  },
  setup (props: Props, { emit } :SetupContext) {
    const editText = ref('')

    function handleStartEditTodo (todo: Todo) {
      editText.value = todo.text.trim()
      emit('onStartEditTodo', todo)
    }
    function handleEndEditTodo (todo: Todo) {
      if (!props.todoBeingEdited) {
        return
      }
      let text = editText.value.trim()
      if (text) {
        todo.text = text
        emit('onEndEditTodo', todo)
      } else {
        emit('onDestroyTodo', todo.id)
      }
    }
    function handleCancelEditTodo (todo: Todo) {
      emit('onEndEditTodo', todo)
    }
    function handleDestroyTodo (todo: Todo) {
      emit('onDestroyTodo', todo.id)
    }

    return {
      editText,
      handleStartEditTodo,
      handleEndEditTodo,
      handleCancelEditTodo,
      handleDestroyTodo
    }
  },
  directives: {
    'todo-focus': function (el: any, binding: any) {
      if (binding.value) {
        el.focus()
      }
    }
  }
})
</script>

// angular-todolist/src/app/Todo/todo.component.ts
import { Component, Input, Output, EventEmitter, ElementRef, Renderer } from '@angular/core';

import {Todo} from '../todo';
@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html'
  })
export class TodoComponent {
  @Input() todo: Todo;
  @Input() todoBeingEdited: any;
  @Output() onToggleTodo = new EventEmitter();
  @Output() onStartEditTodo = new EventEmitter();
  @Output() onEndEditTodo = new EventEmitter();
  @Output() onDestroyTodo = new EventEmitter();
  public editText: string;
  private editField: ElementRef;

  constructor(private el: ElementRef, private renderer: Renderer) {
    this.editField = el.nativeElement.children;
  }

  handleToggleTodo(todo): void {
    this.onToggleTodo.emit(todo.id);
  }

  handleStartEditTodo(todo): void {
    this.editText = todo.text;
    this.onStartEditTodo.emit(todo);
    this.editField[1].focus();
  }

  handleEndEditTodo(todo): void {
    if (!this.todoBeingEdited) {
      return;
    }
    const text: string = this.editText.trim();
    if (text) {
      todo.text = text;
      this.onEndEditTodo.emit(todo);
    } else {
      this.onDestroyTodo.emit(todo.id);
    }
  }

  handleCancelEditTodo(todo): void {
    this.onEndEditTodo.emit(todo);
  }

  handleDestroyTodo(todo): void {
    this.onDestroyTodo.emit(todo.id);
  }

}

<div class="view">
  <input class="toggle" type="checkbox"
    [ngModel]="todo.completed"
    (ngModelChange)="handleToggleTodo(todo)"
  >
  <label
    (dblclick)="handleStartEditTodo(todo)"
  >{{todo.text}}</label>
  <button class="destroy" (click)="handleDestroyTodo(todo)"></button>
</div>
<input class="edit" type="text" #editField
  [(ngModel)]="editText"
  (blur)="handleEndEditTodo(todo)"
  (keydown.enter)="handleEndEditTodo(todo)"
  (keydown.esc)="handleCancelEditTodo(todo)"
>
